import { type Page, expect, test } from '@playwright/test';

/**
 * @fileoverview Test generated by Playwright Codegen tool.
 * This test demonstrates login functionality on the-internet.herokuapp.com.
 * Generated using: npx playwright codegen https://the-internet.herokuapp.com/login
 */

test('Codegen generated login test', async ({ page }: { page: Page }) => {
  // Navigate to login page
  await page.goto('https://the-internet.herokuapp.com/login');

  // Fill in username field
  await page.locator('#username').click();
  await page.locator('#username').fill('tomsmith');
  await page.locator('#username').press('Tab');

  // Fill in password field
  await page.locator('#password').fill('SuperSecretPassword!');

  // Submit login form
  await page.getByRole('button', { name: 'Login' }).click();

  // Verify successful login
  await expect(page.locator('#flash')).toContainText('You logged into a secure area!');

  // Navigate back to login page via logout link
  await page.getByRole('link', { name: 'Logout' }).click();

  // Verify successful logout
  await expect(page.locator('#flash')).toContainText('You logged out of the secure area!');
});
